### ISSUE TITLE
ERR react-csv-downloader@0.1.1 build: `babel src -d dist`

### ISSUE THREAD

**Issue by sesteva** [Terminux/react-csv-downloader#5]
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle react-csv-downloader@0.1.1~prebuild: react-csv-downloader@0.1.1
npm sill lifecycle react-csv-downloader@0.1.1~prebuild: no script for prebuild, continuing
npm info lifecycle react-csv-downloader@0.1.1~build: react-csv-downloader@0.1.1

> react-csv-downloader@0.1.1 build /private/tmp/csv/node_modules/react-csv-downloader
> babel src -d dist

sh: babel: command not found

**Comment by Terminux** [comment]
Thanks for your feedback
